export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

type RowTimestampFields = {
  created_at: string;
  updated_at: string;
};

type StandardInsert<Row extends Record<string, unknown>> = Partial<Row>;
type StandardUpdate<Row extends Record<string, unknown>> = Partial<Row>;

export interface Database {
  public: {
    Tables: {
      branches: {
        Row: {
          address_line1: string;
          address_line2: string | null;
          city: string;
          code: string;
          country: string;
          created_at: string;
          district: string;
          email: string | null;
          hero_image_path: string | null;
          highlights_en: string[];
          highlights_vi: string[];
          id: string;
          is_active: boolean;
          map_url: string | null;
          name_en: string;
          name_vi: string;
          phone: string | null;
          seo_description_en: string;
          seo_description_vi: string;
          seo_title_en: string;
          seo_title_vi: string;
          slug: string;
          sort_order: number;
          story_en: string;
          story_vi: string;
          summary_en: string;
          summary_vi: string;
          timezone: string;
          updated_at: string;
        } & RowTimestampFields;
        Insert: StandardInsert<{
          address_line1: string;
          address_line2: string | null;
          city: string;
          code: string;
          country: string;
          district: string;
          email: string | null;
          hero_image_path: string | null;
          highlights_en: string[];
          highlights_vi: string[];
          id: string;
          is_active: boolean;
          map_url: string | null;
          name_en: string;
          name_vi: string;
          phone: string | null;
          seo_description_en: string;
          seo_description_vi: string;
          seo_title_en: string;
          seo_title_vi: string;
          slug: string;
          sort_order: number;
          story_en: string;
          story_vi: string;
          summary_en: string;
          summary_vi: string;
          timezone: string;
        } & RowTimestampFields>;
        Update: StandardUpdate<{
          address_line1: string;
          address_line2: string | null;
          city: string;
          code: string;
          country: string;
          district: string;
          email: string | null;
          hero_image_path: string | null;
          highlights_en: string[];
          highlights_vi: string[];
          id: string;
          is_active: boolean;
          map_url: string | null;
          name_en: string;
          name_vi: string;
          phone: string | null;
          seo_description_en: string;
          seo_description_vi: string;
          seo_title_en: string;
          seo_title_vi: string;
          slug: string;
          sort_order: number;
          story_en: string;
          story_vi: string;
          summary_en: string;
          summary_vi: string;
          timezone: string;
        } & RowTimestampFields>;
        Relationships: [];
      };
      floors: {
        Row: {
          branch_id: string;
          code: string;
          created_at: string;
          id: string;
          is_active: boolean;
          level_number: number;
          name_en: string;
          name_vi: string;
          notes_en: string;
          notes_vi: string;
          sort_order: number;
          updated_at: string;
        } & RowTimestampFields;
        Insert: StandardInsert<{
          branch_id: string;
          code: string;
          id: string;
          is_active: boolean;
          level_number: number;
          name_en: string;
          name_vi: string;
          notes_en: string;
          notes_vi: string;
          sort_order: number;
        } & RowTimestampFields>;
        Update: StandardUpdate<{
          branch_id: string;
          code: string;
          id: string;
          is_active: boolean;
          level_number: number;
          name_en: string;
          name_vi: string;
          notes_en: string;
          notes_vi: string;
          sort_order: number;
        } & RowTimestampFields>;
        Relationships: [
          {
            foreignKeyName: "floors_branch_id_fkey";
            columns: ["branch_id"];
            isOneToOne: false;
            referencedRelation: "branches";
            referencedColumns: ["id"];
          }
        ];
      };
      room_types: {
        Row: {
          base_price: number;
          code: string;
          cover_image_path: string | null;
          created_at: string;
          description_en: string;
          description_vi: string;
          highlights_en: string[];
          highlights_vi: string[];
          id: string;
          is_active: boolean;
          manual_override_price: number | null;
          name_en: string;
          name_vi: string;
          occupancy_adults: number;
          occupancy_children: number;
          seo_description_en: string;
          seo_description_vi: string;
          seo_title_en: string;
          seo_title_vi: string;
          show_public_price: boolean;
          slug: string;
          sort_order: number;
          size_sqm: number | null;
          story_en: string;
          story_vi: string;
          summary_en: string;
          summary_vi: string;
          updated_at: string;
          weekend_surcharge: number;
          bed_type: string;
        } & RowTimestampFields;
        Insert: StandardInsert<{
          base_price: number;
          bed_type: string;
          code: string;
          cover_image_path: string | null;
          description_en: string;
          description_vi: string;
          highlights_en: string[];
          highlights_vi: string[];
          id: string;
          is_active: boolean;
          manual_override_price: number | null;
          name_en: string;
          name_vi: string;
          occupancy_adults: number;
          occupancy_children: number;
          seo_description_en: string;
          seo_description_vi: string;
          seo_title_en: string;
          seo_title_vi: string;
          show_public_price: boolean;
          slug: string;
          sort_order: number;
          size_sqm: number | null;
          story_en: string;
          story_vi: string;
          summary_en: string;
          summary_vi: string;
          weekend_surcharge: number;
        } & RowTimestampFields>;
        Update: StandardUpdate<{
          base_price: number;
          bed_type: string;
          code: string;
          cover_image_path: string | null;
          description_en: string;
          description_vi: string;
          highlights_en: string[];
          highlights_vi: string[];
          id: string;
          is_active: boolean;
          manual_override_price: number | null;
          name_en: string;
          name_vi: string;
          occupancy_adults: number;
          occupancy_children: number;
          seo_description_en: string;
          seo_description_vi: string;
          seo_title_en: string;
          seo_title_vi: string;
          show_public_price: boolean;
          slug: string;
          sort_order: number;
          size_sqm: number | null;
          story_en: string;
          story_vi: string;
          summary_en: string;
          summary_vi: string;
          weekend_surcharge: number;
        } & RowTimestampFields>;
        Relationships: [];
      };
      rooms: {
        Row: {
          branch_id: string;
          code: string;
          created_at: string;
          floor_id: string;
          id: string;
          is_active: boolean;
          notes_en: string;
          notes_vi: string;
          room_type_id: string;
          status: Database["public"]["Enums"]["room_status"];
          updated_at: string;
        } & RowTimestampFields;
        Insert: StandardInsert<{
          branch_id: string;
          code: string;
          floor_id: string;
          id: string;
          is_active: boolean;
          notes_en: string;
          notes_vi: string;
          room_type_id: string;
          status: Database["public"]["Enums"]["room_status"];
        } & RowTimestampFields>;
        Update: StandardUpdate<{
          branch_id: string;
          code: string;
          floor_id: string;
          id: string;
          is_active: boolean;
          notes_en: string;
          notes_vi: string;
          room_type_id: string;
          status: Database["public"]["Enums"]["room_status"];
        } & RowTimestampFields>;
        Relationships: [
          {
            foreignKeyName: "rooms_branch_id_fkey";
            columns: ["branch_id"];
            isOneToOne: false;
            referencedRelation: "branches";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "rooms_floor_id_fkey";
            columns: ["floor_id"];
            isOneToOne: false;
            referencedRelation: "floors";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "rooms_room_type_id_fkey";
            columns: ["room_type_id"];
            isOneToOne: false;
            referencedRelation: "room_types";
            referencedColumns: ["id"];
          }
        ];
      };
      customers: {
        Row: {
          auth_user_id: string | null;
          created_at: string;
          email: string;
          full_name: string;
          id: string;
          last_seen_at: string | null;
          marketing_consent: boolean;
          marketing_consent_at: string | null;
          marketing_consent_source: string | null;
          notes: string;
          phone: string | null;
          preferred_locale: "vi" | "en";
          source: string;
          updated_at: string;
        } & RowTimestampFields;
        Insert: StandardInsert<{
          auth_user_id: string | null;
          email: string;
          full_name: string;
          id: string;
          last_seen_at: string | null;
          marketing_consent: boolean;
          marketing_consent_at: string | null;
          marketing_consent_source: string | null;
          notes: string;
          phone: string | null;
          preferred_locale: "vi" | "en";
          source: string;
        } & RowTimestampFields>;
        Update: StandardUpdate<{
          auth_user_id: string | null;
          email: string;
          full_name: string;
          id: string;
          last_seen_at: string | null;
          marketing_consent: boolean;
          marketing_consent_at: string | null;
          marketing_consent_source: string | null;
          notes: string;
          phone: string | null;
          preferred_locale: "vi" | "en";
          source: string;
        } & RowTimestampFields>;
        Relationships: [];
      };
      branch_bank_accounts: {
        Row: {
          account_label: string;
          account_name: string;
          account_number: string;
          bank_bin: string;
          bank_name: string;
          branch_id: string;
          created_at: string;
          id: string;
          is_active: boolean;
          is_default: boolean;
          qr_provider: string;
          sort_order: number;
          updated_at: string;
        } & RowTimestampFields;
        Insert: StandardInsert<{
          account_label: string;
          account_name: string;
          account_number: string;
          bank_bin: string;
          bank_name: string;
          branch_id: string;
          id: string;
          is_active: boolean;
          is_default: boolean;
          qr_provider: string;
          sort_order: number;
        } & RowTimestampFields>;
        Update: StandardUpdate<{
          account_label: string;
          account_name: string;
          account_number: string;
          bank_bin: string;
          bank_name: string;
          branch_id: string;
          id: string;
          is_active: boolean;
          is_default: boolean;
          qr_provider: string;
          sort_order: number;
        } & RowTimestampFields>;
        Relationships: [];
      };
      payment_requests: {
        Row: {
          account_name: string;
          account_number: string;
          amount: number;
          bank_bin: string;
          bank_name: string;
          branch_bank_account_id: string;
          branch_id: string;
          confirmation_email_sent_at: string | null;
          confirmation_email_to: string | null;
          confirmation_pdf_generated_at: string | null;
          confirmation_pdf_path: string | null;
          created_at: string;
          created_by: string | null;
          currency: string;
          customer_id: string;
          id: string;
          note: string;
          payment_code: string;
          proof_uploaded_at: string | null;
          public_upload_link_expires_at: string;
          rejected_at: string | null;
          rejected_reason: string;
          reservation_id: string;
          source: string;
          status: Database["public"]["Enums"]["payment_request_status"];
          transfer_content: string;
          updated_at: string;
          updated_by: string | null;
          verified_at: string | null;
        } & RowTimestampFields;
        Insert: StandardInsert<{
          account_name: string;
          account_number: string;
          amount: number;
          bank_bin: string;
          bank_name: string;
          branch_bank_account_id: string;
          branch_id: string;
          confirmation_email_sent_at: string | null;
          confirmation_email_to: string | null;
          confirmation_pdf_generated_at: string | null;
          confirmation_pdf_path: string | null;
          created_by: string | null;
          currency: string;
          customer_id: string;
          id: string;
          note: string;
          payment_code: string;
          proof_uploaded_at: string | null;
          public_upload_link_expires_at: string;
          rejected_at: string | null;
          rejected_reason: string;
          reservation_id: string;
          source: string;
          status: Database["public"]["Enums"]["payment_request_status"];
          transfer_content: string;
          updated_by: string | null;
          verified_at: string | null;
        } & RowTimestampFields>;
        Update: StandardUpdate<{
          account_name: string;
          account_number: string;
          amount: number;
          bank_bin: string;
          bank_name: string;
          branch_bank_account_id: string;
          branch_id: string;
          confirmation_email_sent_at: string | null;
          confirmation_email_to: string | null;
          confirmation_pdf_generated_at: string | null;
          confirmation_pdf_path: string | null;
          created_by: string | null;
          currency: string;
          customer_id: string;
          id: string;
          note: string;
          payment_code: string;
          proof_uploaded_at: string | null;
          public_upload_link_expires_at: string;
          rejected_at: string | null;
          rejected_reason: string;
          reservation_id: string;
          source: string;
          status: Database["public"]["Enums"]["payment_request_status"];
          transfer_content: string;
          updated_by: string | null;
          verified_at: string | null;
        } & RowTimestampFields>;
        Relationships: [];
      };
      payment_proofs: {
        Row: {
          created_at: string;
          customer_id: string;
          file_bucket: string;
          file_name: string;
          file_path: string;
          file_size: number;
          id: string;
          mime_type: string;
          note: string;
          payment_request_id: string;
          review_note: string;
          reviewed_at: string | null;
          reviewed_by: string | null;
          status: Database["public"]["Enums"]["payment_proof_status"];
          updated_at: string;
          uploaded_by_user_id: string | null;
          uploaded_via: string;
        } & RowTimestampFields;
        Insert: StandardInsert<{
          customer_id: string;
          file_bucket: string;
          file_name: string;
          file_path: string;
          file_size: number;
          id: string;
          mime_type: string;
          note: string;
          payment_request_id: string;
          review_note: string;
          reviewed_at: string | null;
          reviewed_by: string | null;
          status: Database["public"]["Enums"]["payment_proof_status"];
          uploaded_by_user_id: string | null;
          uploaded_via: string;
        } & RowTimestampFields>;
        Update: StandardUpdate<{
          customer_id: string;
          file_bucket: string;
          file_name: string;
          file_path: string;
          file_size: number;
          id: string;
          mime_type: string;
          note: string;
          payment_request_id: string;
          review_note: string;
          reviewed_at: string | null;
          reviewed_by: string | null;
          status: Database["public"]["Enums"]["payment_proof_status"];
          uploaded_by_user_id: string | null;
          uploaded_via: string;
        } & RowTimestampFields>;
        Relationships: [];
      };
      analytics_events: {
        Row: {
          branch_id: string | null;
          created_at: string;
          customer_id: string | null;
          entity_id: string | null;
          entity_type: string;
          event_type: Database["public"]["Enums"]["analytics_event_type"];
          id: string;
          locale: string;
          metadata: Json;
          occurred_at: string;
          page_path: string;
          reservation_id: string | null;
          room_type_id: string | null;
          source: string;
          updated_at: string;
        } & RowTimestampFields;
        Insert: StandardInsert<{
          branch_id: string | null;
          customer_id: string | null;
          entity_id: string | null;
          entity_type: string;
          event_type: Database["public"]["Enums"]["analytics_event_type"];
          id: string;
          locale: string;
          metadata: Json;
          occurred_at: string;
          page_path: string;
          reservation_id: string | null;
          room_type_id: string | null;
          source: string;
        } & RowTimestampFields>;
        Update: StandardUpdate<{
          branch_id: string | null;
          customer_id: string | null;
          entity_id: string | null;
          entity_type: string;
          event_type: Database["public"]["Enums"]["analytics_event_type"];
          id: string;
          locale: string;
          metadata: Json;
          occurred_at: string;
          page_path: string;
          reservation_id: string | null;
          room_type_id: string | null;
          source: string;
        } & RowTimestampFields>;
        Relationships: [];
      };
      availability_requests: {
        Row: {
          assigned_to: string | null;
          branch_id: string;
          closed_at: string | null;
          contact_email: string;
          contact_name: string;
          contact_phone: string | null;
          created_at: string;
          created_by: string | null;
          customer_id: string | null;
          guest_count: number;
          handled_at: string | null;
          handled_by: string | null;
          id: string;
          marketing_consent: boolean;
          note: string;
          preferred_locale: "vi" | "en";
          request_code: string;
          response_due_at: string;
          room_type_id: string;
          source: string;
          status: Database["public"]["Enums"]["availability_request_status"];
          stay_end_at: string;
          stay_start_at: string;
          updated_at: string;
          updated_by: string | null;
        } & RowTimestampFields;
        Insert: StandardInsert<{
          assigned_to: string | null;
          branch_id: string;
          closed_at: string | null;
          contact_email: string;
          contact_name: string;
          contact_phone: string | null;
          created_by: string | null;
          customer_id: string | null;
          guest_count: number;
          handled_at: string | null;
          handled_by: string | null;
          id: string;
          marketing_consent: boolean;
          note: string;
          preferred_locale: "vi" | "en";
          request_code: string;
          response_due_at: string;
          room_type_id: string;
          source: string;
          status: Database["public"]["Enums"]["availability_request_status"];
          stay_end_at: string;
          stay_start_at: string;
          updated_by: string | null;
        } & RowTimestampFields>;
        Update: StandardUpdate<{
          assigned_to: string | null;
          branch_id: string;
          closed_at: string | null;
          contact_email: string;
          contact_name: string;
          contact_phone: string | null;
          created_by: string | null;
          customer_id: string | null;
          guest_count: number;
          handled_at: string | null;
          handled_by: string | null;
          id: string;
          marketing_consent: boolean;
          note: string;
          preferred_locale: "vi" | "en";
          request_code: string;
          response_due_at: string;
          room_type_id: string;
          source: string;
          status: Database["public"]["Enums"]["availability_request_status"];
          stay_end_at: string;
          stay_start_at: string;
          updated_by: string | null;
        } & RowTimestampFields>;
        Relationships: [];
      };
      room_holds: {
        Row: {
          availability_request_id: string | null;
          branch_id: string;
          converted_at: string | null;
          created_at: string;
          created_by: string | null;
          customer_id: string | null;
          expires_at: string;
          held_by: string | null;
          hold_code: string;
          hold_window: string;
          id: string;
          notes: string;
          release_reason: string;
          released_at: string | null;
          reservation_id: string | null;
          room_id: string;
          room_type_id: string;
          status: Database["public"]["Enums"]["room_hold_status"];
          stay_end_at: string;
          stay_start_at: string;
          updated_at: string;
          updated_by: string | null;
        } & RowTimestampFields;
        Insert: StandardInsert<{
          availability_request_id: string | null;
          branch_id: string;
          converted_at: string | null;
          created_by: string | null;
          customer_id: string | null;
          expires_at: string;
          held_by: string | null;
          hold_code: string;
          id: string;
          notes: string;
          release_reason: string;
          released_at: string | null;
          reservation_id: string | null;
          room_id: string;
          room_type_id: string;
          status: Database["public"]["Enums"]["room_hold_status"];
          stay_end_at: string;
          stay_start_at: string;
          updated_by: string | null;
        } & RowTimestampFields>;
        Update: StandardUpdate<{
          availability_request_id: string | null;
          branch_id: string;
          converted_at: string | null;
          created_by: string | null;
          customer_id: string | null;
          expires_at: string;
          held_by: string | null;
          hold_code: string;
          id: string;
          notes: string;
          release_reason: string;
          released_at: string | null;
          reservation_id: string | null;
          room_id: string;
          room_type_id: string;
          status: Database["public"]["Enums"]["room_hold_status"];
          stay_end_at: string;
          stay_start_at: string;
          updated_by: string | null;
        } & RowTimestampFields>;
        Relationships: [];
      };
      reservations: {
        Row: {
          availability_request_id: string | null;
          base_price: number;
          booking_code: string;
          branch_id: string;
          cancelled_at: string | null;
          completed_at: string | null;
          confirmed_at: string | null;
          created_at: string;
          created_by: string | null;
          customer_id: string;
          deposit_amount: number;
          guest_count: number;
          hold_id: string | null;
          id: string;
          manual_override_price: number | null;
          nightly_rate: number;
          notes: string;
          primary_room_type_id: string;
          reservation_window: string;
          source: string;
          status: Database["public"]["Enums"]["reservation_status"];
          stay_end_at: string;
          stay_start_at: string;
          total_amount: number;
          updated_at: string;
          updated_by: string | null;
          weekend_surcharge: number;
        } & RowTimestampFields;
        Insert: StandardInsert<{
          availability_request_id: string | null;
          base_price: number;
          booking_code: string;
          branch_id: string;
          cancelled_at: string | null;
          completed_at: string | null;
          confirmed_at: string | null;
          created_by: string | null;
          customer_id: string;
          deposit_amount: number;
          guest_count: number;
          hold_id: string | null;
          id: string;
          manual_override_price: number | null;
          nightly_rate: number;
          notes: string;
          primary_room_type_id: string;
          source: string;
          status: Database["public"]["Enums"]["reservation_status"];
          stay_end_at: string;
          stay_start_at: string;
          total_amount: number;
          updated_by: string | null;
          weekend_surcharge: number;
        } & RowTimestampFields>;
        Update: StandardUpdate<{
          availability_request_id: string | null;
          base_price: number;
          booking_code: string;
          branch_id: string;
          cancelled_at: string | null;
          completed_at: string | null;
          confirmed_at: string | null;
          created_by: string | null;
          customer_id: string;
          deposit_amount: number;
          guest_count: number;
          hold_id: string | null;
          id: string;
          manual_override_price: number | null;
          nightly_rate: number;
          notes: string;
          primary_room_type_id: string;
          source: string;
          status: Database["public"]["Enums"]["reservation_status"];
          stay_end_at: string;
          stay_start_at: string;
          total_amount: number;
          updated_by: string | null;
          weekend_surcharge: number;
        } & RowTimestampFields>;
        Relationships: [];
      };
      reservation_room_items: {
        Row: {
          created_at: string;
          id: string;
          nightly_rate: number;
          notes: string;
          reservation_id: string;
          room_id: string;
          room_type_id: string;
          sort_order: number;
          status: Database["public"]["Enums"]["reservation_room_item_status"];
          stay_end_at: string;
          stay_start_at: string;
          stay_window: string;
          total_amount: number;
          updated_at: string;
        } & RowTimestampFields;
        Insert: StandardInsert<{
          id: string;
          nightly_rate: number;
          notes: string;
          reservation_id: string;
          room_id: string;
          room_type_id: string;
          sort_order: number;
          status: Database["public"]["Enums"]["reservation_room_item_status"];
          stay_end_at: string;
          stay_start_at: string;
          total_amount: number;
        } & RowTimestampFields>;
        Update: StandardUpdate<{
          id: string;
          nightly_rate: number;
          notes: string;
          reservation_id: string;
          room_id: string;
          room_type_id: string;
          sort_order: number;
          status: Database["public"]["Enums"]["reservation_room_item_status"];
          stay_end_at: string;
          stay_start_at: string;
          total_amount: number;
        } & RowTimestampFields>;
        Relationships: [];
      };
      audit_logs: {
        Row: {
          action: string;
          actor_role: string | null;
          actor_user_id: string | null;
          availability_request_id: string | null;
          branch_id: string | null;
          customer_id: string | null;
          entity_id: string | null;
          entity_type: string;
          event_key: string;
          happened_at: string;
          hold_id: string | null;
          id: string;
          metadata: Json;
          reservation_id: string | null;
          room_id: string | null;
          summary: string;
        } & RowTimestampFields;
        Insert: StandardInsert<{
          action: string;
          actor_role: string | null;
          actor_user_id: string | null;
          availability_request_id: string | null;
          branch_id: string | null;
          customer_id: string | null;
          entity_id: string | null;
          entity_type: string;
          event_key: string;
          happened_at: string;
          hold_id: string | null;
          id: string;
          metadata: Json;
          reservation_id: string | null;
          room_id: string | null;
          summary: string;
        } & RowTimestampFields>;
        Update: StandardUpdate<{
          action: string;
          actor_role: string | null;
          actor_user_id: string | null;
          availability_request_id: string | null;
          branch_id: string | null;
          customer_id: string | null;
          entity_id: string | null;
          entity_type: string;
          event_key: string;
          happened_at: string;
          hold_id: string | null;
          id: string;
          metadata: Json;
          reservation_id: string | null;
          room_id: string | null;
          summary: string;
        } & RowTimestampFields>;
        Relationships: [];
      };
    };
    Enums: {
      availability_request_status:
        | "new"
        | "in_review"
        | "quoted"
        | "converted"
        | "closed"
        | "rejected"
        | "expired";
      analytics_event_type:
        | "page_view"
        | "room_view"
        | "branch_view"
        | "cta_click"
        | "gallery_click"
        | "check_availability_click"
        | "hold_room_click"
        | "map_click"
        | "payment_upload";
      payment_proof_status: "uploaded" | "verified" | "rejected";
      payment_request_status: "sent" | "pending_verification" | "verified" | "rejected" | "expired" | "cancelled";
      reservation_room_item_status: "active" | "released" | "cancelled";
      reservation_status: "draft" | "pending_deposit" | "confirmed" | "cancelled" | "completed";
      room_hold_status: "active" | "converted" | "released" | "expired" | "cancelled";
      room_status: "available" | "held" | "booked" | "blocked" | "maintenance";
    };
    Functions: {
      create_reservation: {
        Args: {
          p_actor_role?: string | null;
          p_availability_request_id?: string | null;
          p_base_price?: number | null;
          p_branch_id?: string | null;
          p_created_by?: string | null;
          p_customer_id?: string | null;
          p_deposit_amount?: number | null;
          p_guest_count?: number | null;
          p_hold_id?: string | null;
          p_manual_override_price?: number | null;
          p_metadata?: Json | null;
          p_nightly_rate?: number | null;
          p_notes?: string | null;
          p_primary_room_type_id?: string | null;
          p_room_id?: string | null;
          p_status?: Database["public"]["Enums"]["reservation_status"] | null;
          p_stay_end_at?: string | null;
          p_stay_start_at?: string | null;
          p_total_amount?: number | null;
          p_weekend_surcharge?: number | null;
        };
        Returns: Database["public"]["Tables"]["reservations"]["Row"];
      };
      create_room_hold: {
        Args: {
          p_actor_role?: string | null;
          p_availability_request_id?: string | null;
          p_branch_id: string;
          p_created_by?: string | null;
          p_customer_id?: string | null;
          p_held_by?: string | null;
          p_hold_minutes?: number | null;
          p_metadata?: Json | null;
          p_notes?: string | null;
          p_room_id: string;
          p_room_type_id: string;
          p_stay_end_at: string;
          p_stay_start_at: string;
        };
        Returns: Database["public"]["Tables"]["room_holds"]["Row"];
      };
      find_available_rooms: {
        Args: {
          p_branch_id?: string | null;
          p_limit?: number | null;
          p_room_type_id?: string | null;
          p_stay_end_at?: string | null;
          p_stay_start_at?: string | null;
        };
        Returns: Database["public"]["Tables"]["rooms"]["Row"][];
      };
      log_audit_event: {
        Args: {
          p_action: string;
          p_actor_role?: string | null;
          p_actor_user_id?: string | null;
          p_availability_request_id?: string | null;
          p_branch_id?: string | null;
          p_customer_id?: string | null;
          p_entity_id?: string | null;
          p_entity_type: string;
          p_hold_id?: string | null;
          p_metadata?: Json | null;
          p_reservation_id?: string | null;
          p_room_id?: string | null;
          p_summary: string;
        };
        Returns: Database["public"]["Tables"]["audit_logs"]["Row"];
      };
      release_expired_holds: {
        Args: {
          p_as_of?: string | null;
        };
        Returns: {
          branch_id: string;
          expires_at: string;
          hold_code: string;
          hold_id: string;
          released_at: string | null;
          room_id: string;
          status: Database["public"]["Enums"]["room_hold_status"];
        }[];
      };
      submit_availability_request: {
        Args: {
          p_branch_id: string;
          p_contact_email: string;
          p_contact_name: string;
          p_contact_phone?: string | null;
          p_created_by?: string | null;
          p_guest_count?: number | null;
          p_marketing_consent?: boolean | null;
          p_note?: string | null;
          p_preferred_locale?: string | null;
          p_room_type_id: string;
          p_source?: string | null;
          p_stay_end_at: string;
          p_stay_start_at: string;
        };
        Returns: Database["public"]["Tables"]["availability_requests"]["Row"];
      };
    };
    Views: Record<string, never>;
  };
}

export type Tables = Database["public"]["Tables"];
export type TableRow<TableName extends keyof Tables> = Tables[TableName]["Row"];
export type TableInsert<TableName extends keyof Tables> = Tables[TableName]["Insert"];
export type TableUpdate<TableName extends keyof Tables> = Tables[TableName]["Update"];
export type BranchRow = TableRow<"branches">;
export type FloorRow = TableRow<"floors">;
export type RoomTypeRow = TableRow<"room_types">;
export type RoomRow = TableRow<"rooms">;
export type CustomerRow = TableRow<"customers">;
export type BranchBankAccountRow = TableRow<"branch_bank_accounts">;
export type AvailabilityRequestRow = TableRow<"availability_requests">;
export type PaymentRequestRow = TableRow<"payment_requests">;
export type PaymentProofRow = TableRow<"payment_proofs">;
export type RoomHoldRow = TableRow<"room_holds">;
export type ReservationRow = TableRow<"reservations">;
export type ReservationRoomItemRow = TableRow<"reservation_room_items">;
export type AuditLogRow = TableRow<"audit_logs">;
export type AnalyticsEventRow = TableRow<"analytics_events">;
export type BranchInsert = TableInsert<"branches">;
export type FloorInsert = TableInsert<"floors">;
export type RoomTypeInsert = TableInsert<"room_types">;
export type RoomInsert = TableInsert<"rooms">;
export type CustomerInsert = TableInsert<"customers">;
export type BranchBankAccountInsert = TableInsert<"branch_bank_accounts">;
export type AvailabilityRequestInsert = TableInsert<"availability_requests">;
export type PaymentRequestInsert = TableInsert<"payment_requests">;
export type PaymentProofInsert = TableInsert<"payment_proofs">;
export type RoomHoldInsert = TableInsert<"room_holds">;
export type ReservationInsert = TableInsert<"reservations">;
export type ReservationRoomItemInsert = TableInsert<"reservation_room_items">;
export type AuditLogInsert = TableInsert<"audit_logs">;
export type AnalyticsEventInsert = TableInsert<"analytics_events">;
export type BranchUpdate = TableUpdate<"branches">;
export type FloorUpdate = TableUpdate<"floors">;
export type RoomTypeUpdate = TableUpdate<"room_types">;
export type RoomUpdate = TableUpdate<"rooms">;
export type CustomerUpdate = TableUpdate<"customers">;
export type BranchBankAccountUpdate = TableUpdate<"branch_bank_accounts">;
export type AvailabilityRequestUpdate = TableUpdate<"availability_requests">;
export type PaymentRequestUpdate = TableUpdate<"payment_requests">;
export type PaymentProofUpdate = TableUpdate<"payment_proofs">;
export type RoomHoldUpdate = TableUpdate<"room_holds">;
export type ReservationUpdate = TableUpdate<"reservations">;
export type ReservationRoomItemUpdate = TableUpdate<"reservation_room_items">;
export type AuditLogUpdate = TableUpdate<"audit_logs">;
export type AnalyticsEventUpdate = TableUpdate<"analytics_events">;
export type AvailabilityRequestStatus = Database["public"]["Enums"]["availability_request_status"];
export type PaymentProofStatus = Database["public"]["Enums"]["payment_proof_status"];
export type PaymentRequestStatus = Database["public"]["Enums"]["payment_request_status"];
export type RoomHoldStatus = Database["public"]["Enums"]["room_hold_status"];
export type ReservationStatus = Database["public"]["Enums"]["reservation_status"];
export type ReservationRoomItemStatus = Database["public"]["Enums"]["reservation_room_item_status"];
export type RoomStatus = Database["public"]["Enums"]["room_status"];
export type AnalyticsEventType = Database["public"]["Enums"]["analytics_event_type"];
